<?php

namespace AddOn\Authorization\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class Authorization extends \Chadicus\Slim\OAuth2\Middleware\Authorization
{
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next)
    {
        $request = \AddOn\Authorization\Model\Authorization::addAccessSessionToRequest($request);

        return parent::__invoke($request, $response, $next); // TODO: Change the autogenerated stub
    }
}